/**
 * Copyright 2016 SAP SE
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.09.26 at 11:44:06 AM EEST
//


package com.sap.cloud.sfsf.notification;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eenAlertRequestData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="eenAlertRequestData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="entityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="effectiveStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="publishedAt" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0" form="qualified"/>
 *         &lt;element name="publishedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="repost" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0" form="qualified"/>
 *         &lt;element name="entityKeys" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entityKey" type="{http://notification.event.successfactors.com}param" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="params" minOccurs="0" form="qualified">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="param" type="{http://notification.event.successfactors.com}param" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="eventPayload" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eenAlertRequestData", propOrder = {
    "eventId",
    "entityType",
    "effectiveStartDate",
    "publishedAt",
    "publishedBy",
    "repost",
    "entityKeys",
    "params",
    "eventPayload"
})
public class EenAlertRequestData {

    protected String eventId;
    protected String entityType;
    protected String effectiveStartDate;
    protected Long publishedAt;
    protected String publishedBy;
    protected Boolean repost;
    protected EenAlertRequestData.EntityKeys entityKeys;
    protected EenAlertRequestData.Params params;
    protected Object eventPayload;

    /**
     * Gets the value of the eventId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Sets the value of the eventId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEventId(final String value) {
        eventId = value;
    }

    /**
     * Gets the value of the entityType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEntityType(final String value) {
        entityType = value;
    }

    /**
     * Gets the value of the effectiveStartDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEffectiveStartDate() {
        return effectiveStartDate;
    }

    /**
     * Sets the value of the effectiveStartDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEffectiveStartDate(final String value) {
        effectiveStartDate = value;
    }

    /**
     * Gets the value of the publishedAt property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getPublishedAt() {
        return publishedAt;
    }

    /**
     * Sets the value of the publishedAt property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setPublishedAt(final Long value) {
        publishedAt = value;
    }

    /**
     * Gets the value of the publishedBy property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPublishedBy() {
        return publishedBy;
    }

    /**
     * Sets the value of the publishedBy property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPublishedBy(final String value) {
        publishedBy = value;
    }

    /**
     * Gets the value of the repost property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isRepost() {
        return repost;
    }

    /**
     * Sets the value of the repost property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setRepost(final Boolean value) {
        repost = value;
    }

    /**
     * Gets the value of the entityKeys property.
     *
     * @return
     *     possible object is
     *     {@link EenAlertRequestData.EntityKeys }
     *
     */
    public EenAlertRequestData.EntityKeys getEntityKeys() {
        return entityKeys;
    }

    /**
     * Sets the value of the entityKeys property.
     *
     * @param value
     *     allowed object is
     *     {@link EenAlertRequestData.EntityKeys }
     *
     */
    public void setEntityKeys(final EenAlertRequestData.EntityKeys value) {
        entityKeys = value;
    }

    /**
     * Gets the value of the params property.
     *
     * @return
     *     possible object is
     *     {@link EenAlertRequestData.Params }
     *
     */
    public EenAlertRequestData.Params getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     *
     * @param value
     *     allowed object is
     *     {@link EenAlertRequestData.Params }
     *
     */
    public void setParams(final EenAlertRequestData.Params value) {
        params = value;
    }

    /**
     * Gets the value of the eventPayload property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getEventPayload() {
        return eventPayload;
    }

    /**
     * Sets the value of the eventPayload property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setEventPayload(final Object value) {
        eventPayload = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entityKey" type="{http://notification.event.successfactors.com}param" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entityKey"
    })
    public static class EntityKeys {

        protected List<Param> entityKey;

        /**
         * Gets the value of the entityKey property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entityKey property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntityKey().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Param }
         *
         *
         */
        public List<Param> getEntityKey() {
            if (entityKey == null) {
                entityKey = new ArrayList<>();
            }
            return entityKey;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="param" type="{http://notification.event.successfactors.com}param" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "param"
    })
    public static class Params {

        protected List<Param> param;

        /**
         * Gets the value of the param property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the param property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParam().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Param }
         *
         *
         */
        public List<Param> getParam() {
            if (param == null) {
                param = new ArrayList<>();
            }
            return param;
        }

    }

}
